### ISSUE TITLE
some error with ruamel.yaml 0.18.5

### ISSUE THREAD

**Issue by honeysuckcle** [nukezil/IOMatch#4]
The vision of ruamel.yaml in conda:
ruamel.yaml              0.18.5
ruamel.yaml.clib         0.2.8

The error info is:
```
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    args = get_config()
  File "train.py", line 136, in get_config
    over_write_args_from_file(args, args.c)
  File "/hy-tmp/IOMatch/semilearn/core/utils/misc.py", line 23, in over_write_args_from_file
    dic = yaml.load(f.read(), Loader=yaml.Loader)
  File "/usr/local/miniconda3/envs/iomatch/lib/python3.8/site-packages/ruamel/yaml/main.py", line 1085, in load
    error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  File "/usr/local/miniconda3/envs/iomatch/lib/python3.8/site-packages/ruamel/yaml/main.py", line 1037, in error_deprecation
    raise AttributeError(s)
AttributeError: 
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "/hy-tmp/IOMatch/semilearn/core/utils/misc.py", line 23

        dic = yaml.load(f.read(), Loader=yaml.Loader)
```

**Comment by honeysuckcle** [comment]
The version requirements for yaml in requirement.txt are as follows:
ruamel.yaml>=0.17.21
ruamel.yaml.clib>=0.2.6
Maybe >= need to be changed to ==

**Comment by nukezil** [comment]
Thank you for pointing that out! The requirements file has been updated.
